BasicCommand command            # the basic command to execute
TagElement tag            # tag to be associated with this command
geometry_msgs/PoseStamped offset                 # an extra offset you can set from the UI
string                    orientation_mode
float32                   wait_time                # duration in seconds
string                    map_name
string                    waypoint_name
string                    object_id
string                    routine_id
string                    display_name
int32                     reference_tag_id
string                    reference_tag_family
string                    sensor_id
string                    probe_frame
bool                      replace_existing
